### PR TITLE
Add "reverse" functionality to write to upside-down display

### PR DESCRIPTION
**Pull request by ducoterra**
This request adds a new file "reverser.py" which turns any given bitmask upside-down. It also adds the function "fourletterphat.set_reverse()" which causes "set_digit()" and "set_digit_raw()" to write upside-down to the display.

This came out of a need to quickly reverse the display when I couldn't physically turn the pi.

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Thanks for taking the time to raise a PR for this! Sorry I haven’t got around to reviewing and merging it yet. It’s not forgotten though!

**Comment by ducoterra** [comment]
Totally forgot to follow up - honestly I forgot this was open until @Gadgetoid commented today. I can give it another test on my end - not sure if it still works. I should probably clean up my commit history too - didn't really understand git best practices back then :)

**Comment by Gadgetoid** [comment]
> didn't really understand git best practices back then :)

Haha! We've all been there. I normally just quietly squash merge if it's super messy, but it's not like my own commit history is a picture of perfection.

Now... *finding* a Four Letter HAT to test this is the real challenge. Since this PR was raised we had all chaos ensue, I moved down south and built a home office, and I took as little as I could get away with, and I am a disorganised mess :laughing: :grimacing:

**Comment by ducoterra** [comment]
Closed in favor of https://github.com/pimoroni/fourletter-phat/pull/16

**Comment by ducoterra** [comment]
> Now... _finding_ a Four Letter HAT to test this is the real challenge. Since this PR was raised we had all chaos ensue, I moved down south and built a home office, and I took as little as I could get away with, and I am a disorganised mess laughing grimacing

Ha! I totally understand the disorganized mess part. I still have mine hooked up to the same pi 2 I wrote the original PR on and was able to test it this morning. Opened a new PR with some cleaner code and commits. Let me know if you can find something to test with - otherwise I'll give you remote acces to a pi and you can watch a livestream of my cats trying to knock it off my desk.

**Pull request closed without merging**
